//Expedientes
export const EXPEDIENTES_RECIBIDOS = 'EXPEDIENTES_RECIBIDOS';
export const EXPEDIENTE_RECIBIDO = 'EXPEDIENTE_RECIBIDO';
export const SET_BUSQUEDA = 'SET_BUSQUEDA';
//Noticias
export const NOTICIAS_RECIBIDAS = 'NOTICIAS_RECIBIDAS';