//Expedientes
export const EXPEDIENTES_RECIBIDOS = 'EXPEDIENTES_RECIBIDOS';
export const EXPEDIENTE_RECIBIDO = 'EXPEDIENTE_RECIBIDO';
export const SET_BUSQUEDA = 'SET_BUSQUEDA';
export const BUSCANDO = 'BUSCANDO';
//Noticias
export const NOTICIAS_RECIBIDAS = 'NOTICIAS_RECIBIDAS';
//Fondos
export const FONDOS_RECIBIDOS = 'FONDOS_RECIBIDOS';
export const SET_FONDO = 'SET_FONDO';
//Alertas
export const CREAR_ALERTA = 'CREAR_ALERTA';
export const SET_PROPIEDAD_ALERTA = 'SET_PROPIEDAD_ALERTA';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SET_RESPONSE = 'SET_RESPONSE';
export const CLEAR = 'CLEAR';
export const MODAL_COMPONENT = 'MODAL_COMPONENT';
export const SHOW_ALERT = 'SHOW_ALERT';
export const SHOW_SUCCESS = 'SHOW_SUCCESS';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';